# Spike-sort the Zenodo synthetic dataset using ISO-SPLIT and run benchmarks
# ==========================================================================

- input.dhawale.spikes:
    directory: /Volumes/olveczky_lab_holy2/Ashesh/SimulatedData_drift/simulated drift tetrode dataset (full)
    channel_groups: [0]
    ground_truth_output: /Users/anandsrinivasan/dev/fasrc/data/dh_gt.h5
    # start: 0
    # stop: 1000000
    batch_size: 1000

- checkpoint:
    file: /Users/anandsrinivasan/dev/fasrc/data/dh_snippets.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 20000 # Batch size determines chunking for next stage
    batch_overlap: 10000 # Allows merging of chains across batches

- label_old.isosplit_segfuse:
    wavelet: sym2 # Wavelet used in discrete wavelet transform prior to PCA. For options, see http://wavelets.pybytes.com/
    beta: 1
    n_channels: 4 # Number of channels represented in each snippet (in this case, tetrode)
    n_components: 10 # No. PCA components to use for clustering
    isocut_threshold: 0.9
    min_cluster_size: 10 # Minimum cluster size to consider splitting
    K_init: 200 # Over-clustering initialization
    refine_clusters: False 
    max_iterations_per_pass: 500
    jitter: 0.001 # Additive elementwise Gaussian noise to separate duplicate vectors
    link_threshold: 0.02 # Threshold for linking two nodes across cluster trees (lower means more links)
    link_sig_s: 0.005 # Sigmoidal scale parameter for link weights
    link_sig_k: 0.1 # Sigmoidal offset parameter for link weights (higher means more links)

- checkpoint:
    file: /Users/anandsrinivasan/dev/fasrc/data/dh_linked_snippets_isosplit.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 1000 # Give any batch size here
    batch_overlap: 0 # No overlap required

- finalize

- checkpoint:
    file: /Users/anandsrinivasan/dev/fasrc/data/dh_labeled_snippets_isosplit.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 1000 # Give any batch size here
    batch_overlap: 0 # No overlap required

- benchmark.extrinsic:
    output_file: /Users/anandsrinivasan/dev/fasrc/benchmarks/dh_isosplit.json
    method_name: isosplit-segfuse # Given name for your spike-sorting method
    dataset_name: Dhawale # Given name for your dataset (used for comparison)
    ground_truth_data: /Users/anandsrinivasan/dev/fasrc/data/dh_gt.h5
    max_dt_ground_truth: 4 # ms