# 0. Input: ensure the batch_size is a multiple of the total downsampling factor (in this case, 100)
# Also, ensure the sampling rate is a multiple of the total downsampling factor.

- input.rhd2000:
    sessions: 
        - /Users/rudygelb-bicknell/Documents/implants/eth1/1w_partial/*.rhd
    datetime_pattern: "*_%y%m%d_%H%M%S"
    batch_size: 100000 # Number of samples to load into memory (upper-bounded by stop_sample - stop_sample)
    batch_overlap: 0 # Allows detection of spikes up to the batch boundary
    aux_channels: []

# 1. High-pass first
- preprocess.bandpass:
    order: 4
    highpass: 1.0    # Hz
    lowpass: inf     # Set to infinity to make it purely highpass
    Rp: 0.5          # Ripple parameter  
    Rs: 60           # Stopband attenuation
    type: butter      # Closest available to butterworth
    padding_type: odd
    padding_length: 1000

# 2. Three-stage IIR decimation (5×, 5×, 4×)
- preprocess.decimate:
    order: 4
    factor: 5
    type: iir

- preprocess.decimate:
    order: 4
    factor: 5
    type: iir

- preprocess.decimate:
    order: 4         # Using 8 as specified for sharper cutoff
    factor: 4
    type: iir

# 3. Save the LFP data
- checkpoint:
    file: /Users/rudygelb-bicknell/Documents/implants/eth1/1w_partial/test/lfp.h5
    batch_size: 100000
    batch_overlap: 50000