# Finalize spike labels after performing manual curation (ISO-SPLIT)
# ==================================================================

- load:
    files: /Users/asrvsn/dev/fasrc/olveczky-lab/data/mr_labeled_snippets_new.h5 # Path to labeled snippets HDF5 file
    start: 0
    stop: inf # Process all the data
    batch_size: 10000 # Give any batch size here
    batch_overlap: 0 # No overlap required

- finalize # Do manual curation prior to this step

- checkpoint:
    file: /n/holylfs02/LABS/olveczky_lab/Anand/data/labeled_snippets.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 1000 # Give any batch size here
    batch_overlap: 0 # No overlap required

# Optional: compute quality metrics 

- benchmark.intrinsic:
    dataset_name: r4_210612_195804 # Given name for your dataset (used for comparison)
    method_name: fast_isosplit # Given name for your spike-sorting method
    output_file: /n/holylfs02/LABS/olveczky_lab/Anand/metrics/fast_isosplit.json
    refractory_period: 2
    amplitude_cutoff: 50
    n_components: 10 # Should be same as in feature transform used for clustering
    wavelet: sym2 # Should be same as in feature transform used for clustering
    beta: 1 # Should be same as in feature transform used for clustering
    n_channels: 4
    knn: 100