# Label multiple snippeted files 
# ==============================

- load:
    files: 
        - /Users/asrvsn/dev/fasrc/olveczky-lab/data/mr_snippets.h5 # Path to snippets HDF5 file
        - /Users/asrvsn/dev/fasrc/olveczky-lab/data/mr_snippets.h5 # Path to snippets HDF5 file
    start: 0
    stop: inf # Sort all the data
    batch_size: 100000 # Batch size determines chunking for next stage
    batch_overlap: 50000 

- label_old.isosplit_segfuse:
    n_components: 10 # No. PCA components to use for clustering
    wavelet: sym2 # Wavelet used in discrete wavelet transform prior to PCA. For options, see http://wavelets.pybytes.com/
    beta: 1
    n_channels: 4 # Number of channels represented in each snippet (in this case, tetrode)
    isocut_threshold: 0.9 # Partition threshold; decrease to produce more clusters
    min_cluster_size: 8 # Minimum cluster size to consider splitting
    K_init: 200 # Over-clustering initialization (should be larger than max expected # units)
    refine_clusters: False
    max_iterations_per_pass: 500
    jitter: 0.001 # Additive elementwise Gaussian noise to separate duplicate vectors
    link_threshold: 0.02 # Threshold for linking two nodes across cluster trees (lower means more links)
    link_sig_s: 0.005 # Sigmoidal scale parameter for link weights
    link_sig_k: 0.03 # Sigmoidal offset parameter for link weights (higher means more links)

# OPTIONAL (uncomment): add summary statistics to the data for fast viewing over long time periods in the GUI

# - checkpoint:
#     file: /n/holylfs02/LABS/olveczky_lab/Anand/data/linked_snippets.h5 # Clustered snippets are stored as a single HDF5 file
#     batch_size: 100000 # If using summarization, ensure this matches with the previous one
#     batch_overlap: 50000 # If using summarization, ensure this matches with the previous one

# - postprocess.summarize:
#     downsample_ratio: 1000
#     downsample_data_method: mean
#     downsample_time_method: median
#     isi_subsamples: 10

- checkpoint:
    file: /n/holylfs02/LABS/olveczky_lab/Anand/data/summarized_linked_snippets_isosplit.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 200000 # This batch size can be anything; it sets the sample size for the noise classification step
    batch_overlap: 0 

- postprocess.label_noise_clusters # Auto-label clusters as noisy for GUI 