# Spike-sort MEARec synthetic data using SPC
# ==========================================

- input.synthetic.mearec.spikes:
    templates_file: /Users/anandsrinivasan/dev/fasrc/ephys2/ephys2/tests/data/templates_50_tetrode_18-02-2022_19-52.h5
    ground_truth_output: /Users/anandsrinivasan/dev/fasrc/data/mr_gt_spc.h5
    n_tetrodes: 1
    n_units_per_tetrode: 8
    min_firing_rate: 0.1 # Hz
    max_firing_rate: 1.0 # Hz
    refractory_period: 1.5 # ms
    sampling_rate: 20000 # Hz
    n_samples: 26000
    batch_size: 1000
    noise_std: 0.4
    seed: 0

- checkpoint:
    file: /Users/anandsrinivasan/dev/fasrc/data/mr_snippets_spc.h5 # Snippets are stored as a single HDF5 file
    batch_size: 10000 # Batch size determines chunking for next stage
    batch_overlap: 5000 # Allows merging of chains across batches

- label_old.spc_segfuse:
    t_min: 0.00
    t_max: 0.10
    n_temps: 11
    knn: 11
    cycles: 300
    metric: euclidean
    link_threshold: 0.02 # Threshold for linking two nodes across cluster trees (lower means more links)
    link_sig_s: 0.005 # Sigmoidal scale parameter for link weights
    link_sig_k: 0.03 # Sigmoidal offset parameter for link weights (higher means more links)

- checkpoint:
    file: /Users/anandsrinivasan/dev/fasrc/data/mr_linked_snippets_spc.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 1000 # Give any batch size here
    batch_overlap: 0 # No overlap required

- finalize

- checkpoint:
    file: /Users/anandsrinivasan/dev/fasrc/data/mr_labeled_snippets_spc.h5 # Clustered snippets are stored as a single HDF5 file
    batch_size: 1000 # Give any batch size here
    batch_overlap: 0 # No overlap required

- benchmark.extrinsic:
    dataset_name: MEARec-8 # Given name for your dataset (used for comparison)
    method_name: spc-segfuse # Given name for your spike-sorting method
    output_file: /Users/anandsrinivasan/dev/fasrc/benchmarks_mr/mr_spc.json
    ground_truth_data: /Users/anandsrinivasan/dev/fasrc/data/mr_gt_spc.h5
    max_dt_ground_truth: 1 # ms