# Run a benchmark with ground-truth
# =================================

- load:
    files: /Users/asrvsn/dev/fasrc/olveczky-lab/data/mr_labeled_snippets_new.h5 # Path to snippets HDF5 file
    start: 0
    stop: inf
    batch_size: 1000 # Batch size determines chunking for next stage; since this is the last step, this has no effect.
    batch_overlap: 0 

- benchmark.extrinsic:
    dataset_name: MEARec-8 # Given name for your dataset (used for comparison)
    method_name: isosplit-segfuse-3 # Given name for your spike-sorting method
    output_file: /Users/anandsrinivasan/dev/fasrc/benchmarks_mr/mr_isosplit_3.json
    ground_truth_data: /Users/anandsrinivasan/dev/fasrc/data/mr_gt.h5
    max_dt_ground_truth: 1 # ms