name: Build Singularity Release

on:
  workflow_dispatch:    # manual trigger
  push:
    branches: [ main ]  # optional auto-run on pushes to main

jobs:
  build-ephys2:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout with full history so tags are visible to build-release.sh
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install Apptainer
      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      # 3. Run your build-release.sh
      - name: Run build-release.sh
        run: |
          chmod +x ./singularity/build-release.sh
          ./singularity/build-release.sh
        env:
          # give git a committer identity for tag creation
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      # 4. Upload the resulting .sif file
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ephys2-sif
          path: ephys2-release-*.sif